name: Deploy kamino-slf-mail to AWS

on:
  push:
    branches:
      - feature/kamino-slf-mail-22

env:
  GOPRIVATE: github.com/mahisoft/kamino-go-commons
  GH_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
  ARTIFACT_BUCKET: kamino-artifacts

jobs:
  cicd-pipeline-aws:
    name: Deploy Serverless mail to AWS
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy:aws
